name: Update dev with main changes

on:
  push:
    branches: [ main ]

jobs:
  update_dev:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Pull dev
        run: git pull origin dev

      - name: Rebase from main
        run: git pull --rebase origin main

      - name: Push to dev
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "pulling in changes from main"
          git push origin dev
